---
# handlers file for grok
- name: reload systemd for grok_exporter
  become: true
  systemd:
    daemon_reload: true

- name: restart grok_exporter
  become: true
  systemd:
    name: grok_exporter.service
    state: restarted

- name: restart haproxy service
  become: true
  systemd:
    name: haproxy.service
    state: restarted
